# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress automation testcases

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [master]

jobs:
    macos-test:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  browser: chrome
                  start: npm run test
                  
    windows-test:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  browser: chrome
                  start: npm run test
